# Generated by Django 3.2 on 2021-04-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('price', models.IntegerField()),
                ('discription', models.TextField(max_length=300)),
                ('image', models.ImageField(default='default.jpg', upload_to='products')),
            ],
        ),
    ]
