# Generated by Django 3.2 on 2021-04-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('designation', models.TextField(max_length=200)),
                ('discription', models.TextField(max_length=300)),
                ('profile', models.ImageField(default='default.jpg', upload_to='profile')),
            ],
        ),
    ]
